workflows:
  android-release:
    name: Android Release

    max_build_duration: 60

    instance_type: linux_x2

    triggering:
      events:
        - push
        - pull_request

      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      flutter: stable

    working_directory: notes_app

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Flutter Version
        script: |
          flutter --version

      - name: Build Information
        script: |
          echo "Workflow : $CM_WORKFLOW_NAME"
          echo "Branch   : $CM_BRANCH"
          echo "Commit   : $CM_COMMIT"
          echo "Build    : $BUILD_NUMBER"
          echo "Project  : $PROJECT_BUILD_NUMBER"

      - name: Install Dependencies
        script: |
          flutter pub get

      - name: Generate Code
        script: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Analyze Code
        script: |
          flutter analyze

      - name: Run Unit Tests
        script: |
          flutter test

      - name: Build Release APK
        script: |
          flutter build apk \
            --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER

      - name: Build Release App Bundle
        script: |
          flutter build appbundle \
            --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - ashul1vats@gmail.com
